#!/bin/sh

SAVE_DIR=$HOME/.inotifaction 
SAVE_LOG=$SAVE_DIR/log
SAVE_PID=$SAVE_DIR/pid
SAVE_ERR=$SAVE_DIR/err
SAVE_SCRIPT_DIR=$SAVE_DIR/scripts

CONFIG_DIR=$HOME/.config/inotifaction
CONFIG=$CONFIG_DIR/config

SAVE_BIN_DIR=$HOME/.local/bin

# Install
chmod u+x inotifactiond
cp inotifactiond "$SAVE_BIN_DIR"
# Add that dir to $PATH

mkdir "$CONFIG_DIR"
cp config "$CONFIG_DIR"
touch "$CONFIG"

mkdir "$SAVE_DIR"
cp LICENSE README.md "$SAVE_DIR"
cp -r scripts "$SAVE_SCRIPT_DIR"
touch "$SAVE_LOG" "$SAVE_PID" "$SAVE_ERR"

# Clean
if [ "$1" = "-c" ]; then
    rm -rf "$PWD"
fi
